src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Repository\BookingRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: BookingRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Booking
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'bookings')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $booker = null;

    #[ORM\ManyToOne(inversedBy: 'bookings')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Ad $ad = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\GreaterThan("today", message:'Doit être ultérieure à aujourd\'hui', groups:['front'])]
    #[Assert\Type('datetime')]
    private ?\DateTimeInterface $startDate = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\GreaterThan(propertyPath:"startDate", message:"La date de départ doit être plus éloignée que la date d'arrivée")]
    #[Assert\Type('datetime')]
    private ?\DateTimeInterface $endDate = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column]
    private ?float $amount = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $comment = null;

    /**
     * Permet d'ajouter la date de création et de calculer le prix de la réservation
     */
    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function prePersist():void
    {
        if(empty($this->createdAt))
        {
            $this->createdAt = new \DateTimeImmutable();

        }
        if(empty($this->amount))
        {
            $this->amount = $this->ad->getPrice()*$this->getDuration();
        }
    }

    public function getDuration():?int
    {
        // la méthode diff des objets dattime fait la différence entre 2 dates et renvoie un objet de type DateInterval
        $diff = $this->endDate->diff($this->startDate);
        return $diff->days;
    }

   /**
     * PErmet de vérifier si les dates sont réservables
     *
     * @return boolean|null
     */
    public function isBookableDates(): ?bool 
    {
        // connaîtres les dates impossibles pour l'annonce (voir dans Ad)
        $notAvailableDays = $this->ad->getNotAvailableDays();
        // comparer les dates choisies avec les dates impossible 
        $bookingDays = $this->getDays();
        // transfomer des objets dateTime en tableau de chaines de caractères pour les journées (pour faciliter la comparaison)
        $days = array_map(function($day){
            return $day->format('Y-m-d');
        },$bookingDays);

        $notAvailable = array_map(function($day){
            return $day->format('Y-m-d');
        },$notAvailableDays);

        foreach($days as $day)
        {
            if(array_search($day, $notAvailable) !== false) return false;
        }

        return true;
    }

    /**
     * Permet de récup un tableau des journées qui correspondent à ma réservation
     *
     * @return array|null
     */
    public function getDays(): ?array
    {
        $resultat = range(
            $this->startDate->getTimestamp(),
            $this->endDate->getTimestamp(),
            24 * 60 * 60
        );
        $days = array_map(function($dayTimestamp){
            return new \DateTime(date('Y-m-d',$dayTimestamp));
        },$resultat);

        return $days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[UniqueEntity(fields:['email'], message: "Un autre utilisateur possède déjà cette adresse e-mail, merci de la modifier")]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\Email(message: "Veuillez renseigner une adresse e-mail valide")]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[Assert\Length(min: 8, max: 255, minMessage: "Votre mot de passe doit faire plus de 8 caractères")]
    private ?string $password = null;

    #[Assert\EqualTo(propertyPath:"password", message:"Vous n'avez pas correctement confirmé votre mot de passe")]
    public ?string $passwordConfirm = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Vous devez renseigner votre prénom")]
    private ?string $firstName = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Vous devez renseigner votre nom de famille")]
    private ?string $lastName = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\Image(mimeTypes:["image/png","image/jpeg","image/jpg","image/gif"], mimeTypesMessage:"Vous devez upload un fichier jpg, jpeg, png ou gif")]
    #[Assert\File(maxSize:"1024k", maxSizeMessage:"La taille du fichier est trop grande")]
    private ?string $picture = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(min: 10, max: 255, minMessage:"Votre introduction doit faire plus de 10 caractères", maxMessage:"Votre introduction ne doit pas faire plus de 255 caractères")]
    private ?string $introduction = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\Length(min: 100, minMessage:"Votre description doit faire plus de 100 caractères")]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Ad::class)]
    private Collection $ads;

    #[ORM\OneToMany(mappedBy: 'booker', targetEntity: Booking::class)]
    private Collection $bookings;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Permet d'initialiser le slug automatiquement
     *
     * @return void
     */
    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function initializeSlug():void
    {
        if(empty($this->slug))
        {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName.' '.$this->lastName.' '.uniqid());
        }
    }

    /**Permet d'obtenir le nom complet de l'utilisateur */
    public function getFullName():string
    {
        return "{$this->firstName} {$this->lastName}";
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection<int, Ad>
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads->add($ad);
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->removeElement($ad)) {
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Booking>
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings->add($booking);
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\CommentType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BookingController extends AbstractController
{
    #[Route('/ads/{slug}/book', name: 'booking_create')]
    #[IsGranted('ROLE_USER')]
    public function book(Ad $ad, Request $request, EntityManagerInterface $manager): Response
    {
        $booking = new Booking();
        $form = $this->createForm(BookingType::class, $booking);
        $form->handleRequest($request);// vérifie si formulaire soumis et validé (état)

        if($form->isSubmitted() && $form->isValid())
        {
            //traitement
            $user = $this->getUSer();// je suis certain qu'il y a un user car j'ai sécurisé la fonction
            $booking->setBooker($user)
                ->setAd($ad);

            //vérifier les disponibilité des dates + message d'erreur
            if(!$booking->isBookableDates()){
                $this->addFlash(
                    'warning',
                    'Les dates que vous avez choisies ne peuvent être réservées car elles sont déjà prises'
                );
            }else{
                $manager->persist($booking);
                $manager->flush();

                return $this->redirectToRoute('booking_show',['id'=>$booking->getId(), 'withAlert'=>true]); // j'ai un id comme il a été flush
            }
        }

        return $this->render('booking/book.html.twig', [
            'ad' => $ad,
            'myform'=>$form->createView()
        ]);
    }

    /**
     * Permet l'affcihage de la page de réservation
     */
    #[Route("/booking/{id}", name:"booking_show")]
    #[IsGranted("ROLE_USER")]
    public function show(Booking $booking, Request $request, EntityManagerInterface $manager ): Response
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $comment->setAd($booking->getAd())
                ->setAuthor($this->getUser());

            $manager->persist($comment);
            $manager->flush();

            $this->addFlash(
                'success',
                'Votre message a bien été pris en compte'
            );
        }
        return $this->render("booking/show.html.twig",[
            'booking'=>$booking,
            'myForm' => $form->createView()
        ]);
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réserver l'annonce: {{ad.title}}{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vanillajs-datepicker@1.1.4/dist/css/datepicker-bs4.min.css">
{% endblock %}

{% block body %}
    <div class="container full">
        <h1>Réservation de l'annonce: {{ad.title}}</h1>
        <p>Vous êtes sur le point de réserver le bien <strong>{{ad.author.fullName}}</strong></p>
        {{form_start(myform)}}
            <div class="bg-light p-3">
                <div class="row">
                    <div class="col">
                        {{form_row(myform.startDate)}}
                    </div>
                     <div class="col">
                        {{form_row(myform.endDate)}}
                    </div>
                </div>
                <h4>Montant du séjour: <span id="amount">...</span></h4>
                <span id="days">0 <span>nuit(s) à {{ad.price}}&euro; /nuit</span></span>
                <h4 class="mt-3"> Vous avez un commentaire ?</h4>
                {{form_row(myform.comment)}}
            </div>
            <h2 class="mt-3">Vous avez terminé ! </h2>
            <button class="btn btn-success" type="submit">Réserver</button>
        {{form_end(myform)}}
    </div>
{% endblock %}

{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/vanillajs-datepicker@1.1.4/dist/js/datepicker.min.js"></script>
    <script>
        const bookingStartDate = document.querySelector('#booking_startDate')
        const bookingEndDate = document.querySelector('#booking_endDate')
        const datePickerStart = new Datepicker(bookingStartDate,{
            format: 'dd/mm/yyyy',
            datesDisabled: [
                {% for day in ad.notAvailableDays %}
                    "{{day.format('d/m/Y')}}",
                {% endfor %}
            ],
            minDate: new Date()
        })
        const datePickerEnd = new Datepicker(bookingEndDate,{
            format: 'dd/mm/yyyy',
            datesDisabled: [
                {% for day in ad.notAvailableDays %}
                    "{{day.format('d/m/Y')}}",
                {% endfor %}
            ],
            minDate: new Date()
        })

        bookingStartDate.addEventListener('changeDate', ()=>{
            calculateAmount()
        })

        bookingEndDate.addEventListener('changeDate', ()=>{
            calculateAmount()
        })

        const calculateAmount = () => {
            let bookingStartDate = document.querySelector('#booking_startDate')
            let bookingEndDate = document.querySelector('#booking_endDate')
            const endDate = new Date(bookingEndDate.value.replace(/(\d+)\/(\d+)\/(\d{4})/,'$3-$2-$1'))
            const startDate = new Date(bookingStartDate.value.replace(/(\d+)\/(\d+)\/(\d{4})/,'$3-$2-$1'))
            if(startDate && endDate && startDate < endDate)
            {
                const interval = endDate.getTime() - startDate.getTime()
                const days = interval / (24*60*60*1000)
                const amount = days * {{ad.price}}

                const myDays = document.querySelector('#days')
                const myAmount = document.querySelector('#amount')
                myDays.innerHTML = days+'nuit(s)'
                myAmount.innerHTML = amount.toLocaleString('fr-FR')+'€'
            }
        }

    </script>
{% endblock %}

templates/booking/show.html.twig
{% extends "base.html.twig" %}

{% block title %}Réservation n°{{booking.id}}{% endblock %}

{% block body %}
    <div class="container full">
        <h1>Votre réservation n°{{booking.id}}</h1>
        {% if app.request.query.get('withAlert') %}
            <div class="alert alert-success">
                <h4 class="alert-heading">Bravo !</h4>
                <p>
                Votre réservation auprès de <strong><a href="{{path('user_show',{'slug': booking.ad.author.slug})}}">{{booking.ad.author.fullname}}</a></strong>pour l'annonce <strong><a href="{{path('ads_show',{'slug':booking.ad.slug})}}">{{booking.ad.title}}</a></strong> a bien été prise en compte !</p>
            </div>
        {% endif %}
        
        <div class="row">
            <div class="col">
                <div class="bg-light p-3">
                    <h2>Détails</h2>
                    <dl class="row">
                        <dt class="col-md-4">Numéro</dt>
                        <dd class="col-md-8">{{booking.id}}</dd>
                        <dt class="col-md-4">Date d'arrivée</dt>
                        <dd class="col-md-8">{{booking.startDate | date('d/m/Y')}}</dd>
                        <dt class="col-md-4">Date de départ</dt>
                        <dd class="col-md-8">{{booking.endDate | date('d/m/Y')}}</dd>
                        <dt class="col-md-4">Nombre de nuits</dt>
                        <dd class="col-md-8">{{booking.duration}}</dd>
                        <dt class="col-md-4">Montant total</dt>
                        <dd class="col-md-8">{{booking.amount}}&euro;</dd>
                        <dt class="col-md-4">Commentaire</dt>
                        <dd class="col-md-8">{{booking.comment | raw | nl2br }}</dd>
                    </dl>
                    <hr>
                    <h2>Votre hôte</h2>
                    <div class="row mb-3">
                         <div class="col-3">
                            {% if booking.ad.author.picture %}
                                <img src="/uploads/{{booking.ad.author.picture}}" alt="avatar de {{booking.ad.author.fullName}}" class="avatar avatar-medium">
                            {% else %}
                                <img src="http://picsum.photos/300/300" alt="avatar de {{booking.ad.author.fullName}}" class="avatar avatar-medium">
                            {% endif %}
                        </div>
                        <div class="col-9 mb-3">
                            <h4>
                                <a href="{{path('user_show',{'slug': booking.ad.author.slug})}}">{{booking.ad.author.fullName}}</a>
                            </h4>
                            <span class="badge bg-primary">{{booking.ad.author.ads | length}} annonce(s)</span>
                        </div>
                        {{booking.ad.author.description | raw | nl2br}}
                        <a href="{{path('user_show',{'slug': booking.ad.author.slug})}}" class="btn btn-primary">Plus d'info sur {{booking.ad.author.firstName}}</a>
                    </div>
                </div>
                <div class="bg-light p-3" id="comment">
                    <h2>Votre avis compte! </h2>
                    {% if date() > date(booking.endDate) %}
                        {% set comment = booking.ad.commentFromAuthor(app.user) %}
                        {% if comment is not null %}
                            <blockquote>
                                {{comment.content  | nl2br }}
                            </blockquote>
                            <strong>Note: </strong>{% include "partials/rating.html.twig" with {'rating': comment.rating} %}
                        {% else %}
                            {# formulaire #}
                            {{form_start(myForm)}}
                                {{form_widget(myForm)}}
                                <button type="submit" class="btn btn-success">Confirmer</button>
                            {{form_end(myForm)}}
                        {% endif %}
                    {% else %}
                        <p>Vous ne pourrez pas noter cette annonce tant que votre voyage ne sera pas complet</p>
                    {% endif %}
                </div>


            </div>
            <div class="col">
                <div class="bg-light p-3">
                    <h2>Votre hébergement</h2>
                    <h4>
                        <a href="{{path('ads_show',{'slug': booking.ad.slug})}}">{{booking.ad.title}}</a>
                    </h4>
                    <img src="{{booking.ad.coverImage}}" alt="Image de {{booking.ad.title}}" class="img-fluid">
                    <a href="{{path('ads_show',{'slug': booking.ad.slug})}}" class="btn btn-primary my-3">Plus d'information</a>
                </div>
            </div>

        </div>

    </div>
{% endblock %}