src/Entity/Ad.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\DBAL\Types\Types;
use App\Repository\AdRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: AdRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[UniqueEntity(fields:['title'],message:"Une autre annonce possède déjà ce titre, merci de la modifier")]
class Ad
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(min:10, max:255, minMessage: "Le titre doit faire plus de 10 caractères", maxMessage:'Le titre ne doit pas faire plus de 255 caractères ')]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\Length(min:20, max:255, minMessage: "Le titre doit faire plus de 20 caractères", maxMessage:'Le titre ne doit pas faire plus de 255 caractères ')]
    private ?string $introduction = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\Length(min:100,  minMessage: "Le titre doit faire plus de 100 caractères")]
    private ?string $content = null;

    #[ORM\Column(length: 255)]
    #[Assert\Url(message: "Veuillez rendre une url valide")]
    private ?string $coverImage = null;

    #[ORM\Column]
    private ?int $rooms = null;

    #[ORM\OneToMany(mappedBy: 'ad', targetEntity: Image::class, orphanRemoval: true)]
    #[Assert\Valid()]
    private Collection $images;

    #[ORM\ManyToOne(inversedBy: 'ads')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $author = null;

    //récupération des réservations de l'annonce
    #[ORM\OneToMany(mappedBy: 'ad', targetEntity: Booking::class)]
    private Collection $bookings;

    #[ORM\OneToMany(mappedBy: 'ad', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function initializeSlug():void{
        if (empty($this->slug)){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    /**
     * Permet de récup la note d'une annonce
     *
     * @return integer
     */
    public function getAvgRatings(): int 
    {
        // calculer la sommes des notations
        // fonction array_reduce - permet réduire le tableau à une saule valeur (attention il faut un tableau pas une array Collection, pour la transformation on va utiliser toArray() - 2ème paramètre c'est la foonction pour chaque valeur, le 3ème valeur par défaut)
        $sum = array_reduce($this->comments->toArray(), function($total, $comment){
            return $total + $comment->getRating();
        },0);

        // faire la division pour avoir la moyenne (ternaire)
        if(count($this->comments) > 0) return $moyennne = round($sum / count($this->comments));
        return 0;
    }

    /**
     * PErmet d'obtenir un tableau des jours qui ne sont pas disponibles pour cette annonce
     *
     * @return array|null
     */
    public function getNotAvailableDays(): ?array
    {
        $notAvailableDays=[];
        foreach($this->bookings as $booking)
        {
            //calcul entre jours de départ et d'arrivée 
            //fonction range crée un tableau qui contient chaque étape existente entre deux nombres 
            // $result = range(10,20,2) -> donnera 10,12,14,16,18,20
            $resultat = range($booking->getStartDate()->getTimestamp(), $booking->getEndDate()->getTimestamp(), 24*60*60);
            $days = array_map(function($dayTimestamp){
                return new \DateTime(date('Y-m-d', $dayTimestamp));
            }, $resultat);
            $notAvailableDays = array_merge($notAvailableDays, $days);
        }
        return $notAvailableDays;
    }

   /**
     * Permet de récupérer le commentaire d'un auteur par rapport à une annnonce
     *
     * @param User $author
     * @return Comment|null
     */
    public function getCommentFromAuthor(User $author): ?Comment
    {
        foreach($this->comments as $comment){
            if($comment->getAuthor() === $author) return $comment;
        }

        return null;
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection<int, Image>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection<int, Booking>
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings->add($booking);
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[UniqueEntity(fields:['email'], message: "Un autre utilisateur possède déjà cette adresse e-mail, merci de la modifier")]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\Email(message: "Veuillez renseigner une adresse e-mail valide")]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[Assert\Length(min: 8, max: 255, minMessage: "Votre mot de passe doit faire plus de 8 caractères")]
    private ?string $password = null;

    #[Assert\EqualTo(propertyPath:"password", message:"Vous n'avez pas correctement confirmé votre mot de passe")]
    public ?string $passwordConfirm = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Vous devez renseigner votre prénom")]
    private ?string $firstName = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Vous devez renseigner votre nom de famille")]
    private ?string $lastName = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\Image(mimeTypes:["image/png","image/jpeg","image/jpg","image/gif"], mimeTypesMessage:"Vous devez upload un fichier jpg, jpeg, png ou gif")]
    #[Assert\File(maxSize:"1024k", maxSizeMessage:"La taille du fichier est trop grande")]
    private ?string $picture = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(min: 10, max: 255, minMessage:"Votre introduction doit faire plus de 10 caractères", maxMessage:"Votre introduction ne doit pas faire plus de 255 caractères")]
    private ?string $introduction = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\Length(min: 100, minMessage:"Votre description doit faire plus de 100 caractères")]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Ad::class)]
    private Collection $ads;

    #[ORM\OneToMany(mappedBy: 'booker', targetEntity: Booking::class)]
    private Collection $bookings;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Permet d'initialiser le slug automatiquement
     *
     * @return void
     */
    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function initializeSlug():void
    {
        if(empty($this->slug))
        {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName.' '.$this->lastName.' '.uniqid());
        }
    }

    /**Permet d'obtenir le nom complet de l'utilisateur */
    public function getFullName():string
    {
        return "{$this->firstName} {$this->lastName}";
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection<int, Ad>
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads->add($ad);
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->removeElement($ad)) {
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Booking>
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings->add($booking);
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

templates/ad/_ad.html.twig
{% set url = path('ads_show', {'slug':ad.slug}) %}
<div class="col-md-4">
    <div class="card bg-light mb-3">
        <div class="card-header text-center">
            {{ad.rooms}} chambre(s),  <strong>{{ad.price}}€ / nuit</strong>
            <br>
            {% if ad.comments | length > 0 %}
                {% include "partials/rating.html.twig" with {'rating': ad.avgRatings} %} 
                ({{ad.comments | length}} avis )
            {% else %}
                <small> PAs encore noté</small>
            {% endif %}
        </div>
        <a href="{{url}}">
            <img class=" starsimg" src="{{ad.coverImage}}" alt="image de l'annonce {{ad.title}}">
        </a>
        <div class="card-body">
            <h4 class="card-title">
                {{ad.title}}
            </h4>
            <p class="card-text">{{ad.introduction}}</p>
            <a href="{{url}}" class="btn btn-secondary">En savoir plus</a>
            {% if (app.user and app.user==ad.author)or is_granted('ROLE_ADMIN') %}
                <a href="{{path('ads_edit',{'slug': ad.slug})}}" class="btn btn-warning my-2">Modifier</a>
             
            {% endif %}
        </div>
    </div>
</div>

templates/ad/_collection.html.twig
{% block _annonce_images_widget %}
{# Définition du champ annonce_image, la variable form correspond au champ annonce_image #}
    <p>Ici, vous pouvez ajouter vos propres images</p>
    {{form_widget(form)}}
    <input type="hidden" id="widgets-counter" value="0">
    <div class="form-group">
        <button type="button" id="add-image" class="btn btn-primary">Ajouter une image</button>
    </div>
{% endblock %}

{% block _annonce_images_entry_row %}
{# entry précie le entry_type de notre annonceType au niveau de la collection - donc chaque formulaire de ImageType #}
    {{form_widget(form)}}
    {# cela m'a permis de juste afficher le widget et plus les label __name__ (0,1,2,3,...) #}
{% endblock %}

{% block _annonce_images_entry_widget %}
    <div class="form-group my-2" id="block_{{id}}">
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col">
                        {{form_widget(form.url)}}
                        {{form_errors(form.url)}}
                    </div>
                    <div class="col">
                        {{form_widget(form.caption)}}
                        {{form_errors(form.caption)}}
                    </div>
                </div>
            </div>
            <div class="col-2">
                <button type="button" class="btn btn-danger" data-action="delete" data-target="#block_{{id}}">X</button>
            </div>
        </div>
    </div>
{% endblock %}

templates/ad/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}Modification de l'annonce : {{ad.title}}{% endblock %}

{# {% form_theme myform 'bootstrap_5_layout.html.twig' %} #}
{% form_theme myform 'ad/_collection.html.twig' %}

{% block body %}
    <div class="container">
        <h1>Modification de l'annonce : {{ad.title}}</h1>
        {{form_start(myform)}}
            <div class="container">
                <div>
                    {{form_widget(myform)}}
                </div>
            </div>
            <button type="submit" class="btn btn-warning mt-3">Modifier</button>
        {{form_end(myform)}}
    </div>
{% endblock %}


{% block javascripts %}
    {{encore_entry_script_tags('annonce')}}
{% endblock %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos annonces{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            {% for ad in pagination.data %}
                {% include "ad/_ad.html.twig" %}
            {% endfor %}
        </div>

        {{pagination.display()}}
    </div>
{% endblock %}

templates/ad/new.html.twig
{% extends "base.html.twig" %}

{% block title %}Création d'une annonce{% endblock %}

{# {% form_theme myform 'bootstrap_5_layout.html.twig' %} #}
{% form_theme myform _self %}

{% block body %}
    <div class="container">
        <h1>Création d'une nouvelle annonce</h1>
        {{form_start(myform)}}
            <div class="container">
                <div>
                    {{form_widget(myform)}}
                </div>
            </div>
            <button type="submit" class="btn btn-primary mt-3">Création d'une annonce</button>
        {{form_end(myform)}}
    </div>
{% endblock %}

{% block _annonce_images_widget %}
{# Définition du champ annonce_image, la variable form correspond au champ annonce_image #}
    <p>Ici, vous pouvez ajouter vos propres images</p>
    {{form_widget(form)}}
    <input type="hidden" id="widgets-counter" value="0">
    <div class="form-group">
        <button type="button" id="add-image" class="btn btn-primary">Ajouter une image</button>
    </div>
{% endblock %}

{% block _annonce_images_entry_row %}
{# entry précie le entry_type de notre annonceType au niveau de la collection - donc chaque formulaire de ImageType #}
    {{form_widget(form)}}
    {# cela m'a permis de juste afficher le widget et plus les label __name__ (0,1,2,3,...) #}
{% endblock %}

{% block _annonce_images_entry_widget %}
    <div class="form-group my-2" id="block_{{id}}">
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col">
                        {{form_widget(form.url)}}
                        {{form_errors(form.url)}}
                    </div>
                    <div class="col">
                        {{form_widget(form.caption)}}
                        {{form_errors(form.caption)}}
                    </div>
                </div>
            </div>
            <div class="col-2">
                <button type="button" class="btn btn-danger" data-action="delete" data-target="#block_{{id}}">X</button>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script>
        const addImage = document.querySelector('#add-image')
        addImage.addEventListener('click',()=>{
            // compter combien j'ai de form-group pour les indices ex: annonce_image_0_url
            const widgetCounter = document.querySelector("#widgets-counter")
            const index = +widgetCounter.value // le + permet de transofmer en nombre, value rends tjrs un string 
            const annonceImages = document.querySelector('#annonce_images')
            //recup le prototype des entrées data-prototype
            const prototype = annonceImages.dataset.prototype.replace(/__name__/g, index) // drapeau g pour indiquer que l'on va le faire plusieurs fois 
            //injecter le code dans la div
            annonceImages.insertAdjacentHTML('beforeend', prototype)
            widgetCounter.value = index+1
            handleDeleteButtons() // pour mettre à jour le tablea deletes et ajouter l'évent 
        })
        const updateCounter = () => {
            const count = document.querySelectorAll('#annonce_images div.form-group').length
            document.querySelector('#widgets-counter').value = count
        }
        const handleDeleteButtons = () => {
            var deletes = document.querySelectorAll("button[data-action='delete']")
            deletes.forEach(button => {
                button.addEventListener('click',()=>{
                    const target = button.dataset.target
                    const elementTarget = document.querySelector(target)
                    if(elementTarget){
                        elementTarget.remove() // supprimer l'élément 
                    }
                })
            })
        }
        updateCounter()
        handleDeleteButtons()
    </script>
{% endblock %}

templates/ad/show.html.twig
{% extends 'base.html.twig'%}

{% block title %}Annonces:{{ad.title}}{% endblock %}

{% block body %}
    <div class="annonce-title" style="background-image: url({{ad.coverImage}}">
        <div class="container">
            <h1>{{ad.title}}</h1>
            <p>{{ad.introduction}}</p>
            <p class="h2"> <strong>{{ad.rooms}} chambre(s)</strong> pour <strong>{{ad.price}}</strong>€/nuit</p>
            <a href="{{path('booking_create',{'slug':ad.slug})}}" class="btn btn-primary">Réserver</a>
            {# Gestion de l'annonce #}
            {% if (app.user and app.user==ad.author)or is_granted('ROLE_ADMIN') %}
                <a href="{{path('ads_edit',{'slug': ad.slug})}}" class="btn btn-warning mx-2">Modification de l'annonce</a>
                <a href="{{path('ads_delete',{'slug': ad.slug})}}" class="btn btn-danger mx-2">Supprimer l'annonce</a>
            {% endif %}
            
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-8 mb-3">
                {{ad.content | raw}}

                <div class="bd-example">
                    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="false">
                        <div class="carousel-indicators">
                         {% for image in ad.images %}
                            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="{{loop.index0}}" {% if loop.first %} class="active" aria-current="true" {% endif %} aria-label="Slide {{loop.index}}"></button>
                        {% endfor %} 
                           
                        </div>
                        <div class="carousel-inner">
                            {% for image in ad.images %}
                                <div class="carousel-item {% if loop.first %}active{% endif %}">
                                    <img src="{{image.url}}" class="d-block w-100" alt="image de {{ad.title}}">
                                    <div class="carousel-caption d-none d-md-block">
                                         <h5>{{ad.title}}</h5>
                                        <p>{{image.caption}}</p>
                                    </div>
                                </div>
                            {% endfor %}
                           
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    </div>
                </div>
                {# gestion des comment #}
                <hr>
                {% if ad.comments | length > 0 %}
                    <h2 class="mb-3">Commentaires de nos locataires</h2>
                    <div class="calert alert-info">
                    <h4 class="alert-heading text-center">
                        <div class="row align-items-center">
                            <div class="col">
                                Note globale
                            </div>
                            <div class="col">
                                {% include "partials/rating.html.twig" with {'rating':ad.avgRatings} %}
                                <br>
                                <small>(Cette note est calculée sur {{ad.comments | length}} avis )</small>
                            </div>
                        </div>
                    </h4>
                    </div>

                    {% for comment in ad.comments %}
                        <div class="bg-light mb-3 p-3">
                            <strong>{{comment.author.firstName}}</strong>
                            <blockquote>
                                {{comment.content | raw | nl2br}}
                            </blockquote>
                            <strong>Note donnée : </strong>
                            {% include "partials/rating.html.twig" with {'rating':comment.rating} %}
                        </div>
                    {% endfor %}
                {% else %}
                    <h2>Cette annonce n'a pas encore reçu de commentaires</h2>
                {% endif %}
                
            </div>
            <div class="col">
            {% set a = ad.author %}
                <div class="row">
                    <div class="col-3">
                        <a href="{{path('user_show', {'slug': a.slug})}}">
                            {% if a.picture %}
                                <img src="/uploads/{{a.picture}}" alt="Avatar de{{a.fullName}}" class="avatar avatar-medium">
                            {% else %}
                                 <img src="https://picsum.photos/300/300" alt="Avatar de{{a.fullName}}" class="avatar avatar-medium">
                            {% endif %}
                            
                        </a>
                       
                    </div>
                    <div class="col">
                    <a href="{{path('user_show', {'slug': a.slug})}}">
                        <h3>{{a.fullName}}</h3>
                    </a>
                       <button type="button" class= "btn btn-primary">
                            Annonce(s)<span class="badge badge-primary bg-primary">{{a.ads | length}}</span>
                       </button>
                    </div>
                       {{a.description | raw | nl2br}}
                    

                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    {{parent()}} 
    {# récupérer ce qu'il y a dans le parent dans base.html.twig, si je ne le mets pas ça écrase#}
    <script>
    
    </script>
{% endblock %}